---
title: "R practise functions"
format: html
editor: visual
---

```{r}
library(rvest) # scrape info from websites
library(readr)
library(dplyr)
library(janitor)

```

```{r}
webpage <- rvest::read_html("https://www.pwrc.usgs.gov/BBL/Bander_Portal/login/speclist.php") #scrape info from usgs birdbending website

tbls <- rvest::html_nodes(webpage, "table") %>% 
    rvest::html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    janitor::clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))

head(species, 3)
species <- tbls[[1]] %>% 
  janitor::clean_names() %>% 
  select(alpha_code, common_name) %>% 
  mutate(alpha_code = tolower(alpha_code))

head(species, 3)
```

# Read in data

```{r}
pred <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")
nest <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")
egg <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A4b219711-2282-420a-b1d6-1893fe4a74a6")
```

```{r}
glimpse(pred)
glimpse(nest)
glimpse(egg)
```

```{r}
pred_joined <- left_join(pred,
species,
by = c("species" = 
         "alpha_code"))
```


```{r}
#' Title
#'
#' @param df 
#' @param species 
#'
#' @returns return_df
#' @export
#'
#' @examples 
add_species_name <- function(df,species){
  
return_df <- left_join(df,
species,
by = c("species" = 
         "alpha_code"))
return(return_df)
}
```


  

